In [6]:
import torch
from dataset import ImageDataset

In [7]:
trainset = ImageDataset(data_path='train_data')

In [3]:
max_val = 0
for idx in range(len(trainset)):
    img = trainset[idx][0]
    if torch.max(img).item() > max_val:
        max_val = torch.max(img).item()
max_val

255.0

In [8]:
mean = 0
std = 0
for idx in range(len(trainset)):
    img = trainset[idx][0]
    mean += torch.mean(img, dim=(1, 2))
    std += torch.std(img, dim=(1, 2))

mean /= len(trainset)
std /= len(trainset)

print(mean/255)
print(std/255)

tensor([0.5005, 0.3526, 0.5494])
tensor([0.1493, 0.1340, 0.1123])


In [9]:
print(mean/255)
print(std/255)

tensor([0.5005, 0.3526, 0.5494])
tensor([0.1493, 0.1340, 0.1123])
